Vivek khasiya

Enrollment No: 240280107155

1. Import Numpy

In [115]:
import numpy as np

2. Numpy Array: Array with one dimention → Vectors, Two dimentions → Matrices, Three or more dimentions → Tensor

a. Create numpy array and print it. Use np.array

In [116]:
arr1 = np.array([1,2,3,4,5])
print("one-dimentional arrys:")
print(arr1)

one-dimentional arrys:
[1 2 3 4 5]


b. Create a two-dimentional array and print it.

In [117]:
arr2 =np.array([[1,2,3],[4,5,6]])
print("\n Two-dimensional array:")
print(arr2)


 Two-dimensional array:
[[1 2 3]
 [4 5 6]]


c. Use the shape function to determine the shape of array.

In [118]:
print(f"Shape of 1D Array: {arr1.shape}")
print(f"Shape of 2D Array: {arr2.shape}")

Shape of 1D Array: (5,)
Shape of 2D Array: (2, 3)


d. Use reshape function to convert vector into matrix and matrix into vector

In [119]:
matrix = arr1.reshape(1,5)
print(f"vector to matrix : {matrix}")

vector = arr1.reshape(5,)
print(f"matrix to vector : {vector}")

vector to matrix : [[1 2 3 4 5]]
matrix to vector : [1 2 3 4 5]


3. Creating Arrays

a. Create an array using numpy arange function.

In [120]:
arr =  np.arange(1,20,2)
print(f"array using np.arange() : {arr}")

array using np.arange() : [ 1  3  5  7  9 11 13 15 17 19]


b. Reshape it into a matrix form using reshape function.

In [121]:
arr1 = arr.reshape(2,5)
print(f"reshaped array to matrix \n: {arr1}")

reshaped array to matrix 
: [[ 1  3  5  7  9]
 [11 13 15 17 19]]


c. Create arrays filled with zeros and ones. Use zeros and ones function

In [122]:
zero = np.zeros(6,)
one = np.ones((3,4))

print(f"Array filled with Zeroes : {zero}")
print(f"Array filled with Ones : \n {one}")

Array filled with Zeroes : [0. 0. 0. 0. 0. 0.]
Array filled with Ones : 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


d. Create two arrays with zeros and ones and combine them using

In [123]:
a = np.zeros((3,4))
b = np.ones((3,4))

i. as columns next to each other using column_stack

In [124]:
colStack = np.column_stack((a,b))
print(f"column Stack Concate of Arrays :\n {colStack}")

column Stack Concate of Arrays :
 [[0. 0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 0. 1. 1. 1. 1.]]


In [125]:
rowStack = np.vstack((a,b))
print(f"row Stack Concate of Arrays :\n {rowStack}")

row Stack Concate of Arrays :
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


4. Vectorized Functions

a. Create a matrix of size 3X4 using arrange.

In [126]:
matrix = np.arange(10,46,3)
print(f"matrix : \n{matrix}")

matrix : 
[10 13 16 19 22 25 28 31 34 37 40 43]


b. Add 150 to each element

In [127]:
a = matrix+150
print(f"matrix after adding 150 to each element \n {a}")

matrix after adding 150 to each element 
 [160 163 166 169 172 175 178 181 184 187 190 193]


c. Rise each element to power of 2

In [128]:
b = matrix**2
print(f"Matrix Squared: {b}")

Matrix Squared: [ 100  169  256  361  484  625  784  961 1156 1369 1600 1849]


d. Create the array a ([
    [ 2, 4, 6, 8, 10],
    [12, 14, 16, 18, 20],
    [22, 24, 26, 28, 30],
    [32, 34, 36, 38, 40]
])

In [129]:
a = np.arange(2,41,2).reshape(4,5)
print(a)

[[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]]


e. Use comparison operators (a>6, a==10)

In [130]:
print(f"comparizon : {a>6} \n result: {a[a>6]}")
print(f"comparizon : {a==6} \n result: {a[a==10]}")

comparizon : [[False False False  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]] 
 result: [ 8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40]
comparizon : [[False False  True False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]] 
 result: [10]


f. Use logical operators. ((a < 3) | (a > 8)), ((a > 4) & (a < 7)), (~(a > 6))

In [131]:
print(f"comparizon :\n{(a<3 )| (a>8)} \n result : {a[(a<3 )| (a>8)]}")
print(f"comparizon :\n{(a > 4) & (a < 7)} \n result : {a[(a > 4) & (a < 7)]}")
print(f"comparizon :\n{(~(a > 6))} \n result : {a[(~(a > 6))]}")

comparizon :
[[ True False False False  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]] 
 result : [ 2 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40]
comparizon :
[[False False  True False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]] 
 result : [6]
comparizon :
[[ True  True  True False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]] 
 result : [2 4 6]


5. Array Indexing and Slicing

a. Create an array with 12 elements.

In [132]:
a = np.arange(0,24,2)
print(a)

[ 0  2  4  6  8 10 12 14 16 18 20 22]


b. Make all elements from index 7 to 11 to -1

In [133]:
a[7:12] =-1
print(a)

[ 0  2  4  6  8 10 12 -1 -1 -1 -1 -1]


c. Extract elements at index 2,3,6 positions in one go

In [134]:
print(a[[2,3,6]])

[ 4  6 12]


d. Create a matrix of size 3X4

In [135]:
b = np.arange(10,22).reshape(3,4)
print(b)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


e. Extract 2nd row

In [136]:
print(b[1])

[14 15 16 17]


f. Extract 3rd column

In [137]:
print(b[:,2])

[12 16 20]


g. Extract 1st, 2nd row


In [138]:
print(b[0:2])

[[10 11 12 13]
 [14 15 16 17]]


h. Extract 2nd row, 3rd column

In [139]:
print(b[1,2])

16


i. Extract 1s, 2nd row, first three columns

In [140]:
print(b[0:2,0:3])

[[10 11 12]
 [14 15 16]]


j. set the third row to 1,2,3,4

In [141]:
b[2] = [1,2,3,4]
print(b)

[[10 11 12 13]
 [14 15 16 17]
 [ 1  2  3  4]]


6. Array Indexing and Slicing – Criteria

a. Create two vectors: i. names = np.array(["Rahul", "Simran", "Ritesh", "Simran", "Rahul"]) ii. score = np.array([126, 115, 130, 141, 132])

In [142]:
names = np.array(["Rahul", "Simran", "Ritesh", "Simran", "Rahul"]) 
score = np.array([126, 115, 130, 141, 132])

b. Extract all test scores that are smaller than 130

In [143]:
print(score[score<130])

[126 115]


c. Extract all test scores by Simran

In [144]:
print(score[names == "Simran"])

[115 141]


d. Add 10 points to Rahul’s scores

In [145]:
score[names =="Rahul"] +=10
print(score[names=="Rahul"])

[136 142]


7. Random Numbers:


a. Explore random.choice
Pick multiple values



In [146]:
arr = np.arange(0,100,10)
print(arr)
print(f"Single choices : {np.random.choice(arr)}")
print(f"Multiple choices : {np.random.choice(arr,size=3)}")

[ 0 10 20 30 40 50 60 70 80 90]
Single choices : 0
Multiple choices : [30 10 70]


b. Explore random.normals
syntax:np.random.normal(mean, std_dev, size)

In [147]:
print(np.random.normal(3,2,6))

[ 2.10651706  6.04848327  3.64599959  0.21316612 -1.35666849  0.91220718]


c. Explore random.binomial
syntax : np.random.binomial(trials, probability, size)

In [148]:
print(np.random.binomial(10,0.5,5))

[7 6 4 5 5]


d. Explore random.uniform
syntax : np.random.uniform(low, high, size)


In [149]:
print(np.random.uniform(1,10,5))

[9.65054822 8.60080464 7.72588099 5.85722919 6.28076049]


e. Explore and explain the use of random.seed
Fixes the random number sequence so results are repeatable.


In [150]:
np.random.seed(42)
print(np.random.rand(3))

[0.37454012 0.95071431 0.73199394]


Example without seed

In [151]:
print(np.random.rand(3))

[0.59865848 0.15601864 0.15599452]


8. Statistical Functions: (sum, mean, median, etc…)


a. Create a matrix of size 3X4


In [152]:
a = np.random.randint(1, 30, size=(3, 4))
print(a)


[[11 11 24 21]
 [ 4  8 24  3]
 [22 21  2 24]]


b. Find the sum of all elements


In [153]:
print(np.sum(a))

175


c. Add rows, preserve columns


In [154]:
print(a.sum(axis=0))

[37 40 50 48]


d. Add columns, preserve rows Note: a.sum and np.sum(a) are same

In [155]:
print(np.sum(a, axis=1))

[67 39 69]


mean

In [156]:
print(np.mean(a))

14.583333333333334


median


In [157]:
print(np.median(a))

16.0


row wise mean


In [158]:
print(np.mean(a,axis=1))


[16.75  9.75 17.25]


column wise mean


In [159]:
print(np.mean(a,axis=0))

[12.33333333 13.33333333 16.66666667 16.        ]
